# https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "19:00"
      timezone: "Asia/Tokyo"
    assignees:
      - "masutaka"
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "19:00"
      timezone: "Asia/Tokyo"
    assignees:
      - "masutaka"
    open-pull-requests-limit: 10
